LabConnect/urls.py
from django.contrib import admin
from django.urls import path
from django.views.generic import RedirectView
from Agenda.views import login_user, submit_login, logout_user, agenda, agendamento, data_analysis

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', agenda, name='agenda'),
    path('agendamento', agendamento, name='agendamento'),
    path('login_user', login_user, name='login_user'),
    path('login/submit', submit_login, name='submit_login'),
    path('logout', logout_user, name='logout_user'),
    path('data-analysis', data_analysis, name= 'data-analysis'),
]

Agenda/models.py
from django.db import models
from django.contrib.auth.models import User

class Escola(models.Model):
    """Classe representando uma escola"""
    id_escola = models.AutoField(primary_key=True)
    nome = models.CharField(max_length=100)

    def __str__(self):
        return f'{self.nome}'

class Turma(models.Model):
    """Classe representando a turma de uma escola"""
    id_turma = models.AutoField(primary_key=True)
    nome = models.CharField(max_length=100)
    escola = models.ForeignKey(Escola, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.nome}'

class Laboratorio(models.Model):
    """Classe representando um laboratório da escola"""
    id_laboratorio = models.AutoField(primary_key=True)
    nome = models.CharField(max_length=100)
    escola = models.ForeignKey(Escola, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.nome}'

class Disciplina(models.Model):
    """Classe representando uma disciplina da escola"""
    id_disciplina = models.AutoField(primary_key=True)
    nome = models.CharField(max_length=100)

    def __str__(self):
        return f'{self.nome}'

class Agenda(models.Model):
    """Clsse representando um agendamento realizado"""
    HORARIO_CHOICES=[('1','07:30h às 08:20h'),
                     ('2','08:20h às 09:10h'),
                     ('3','09:10h às 10:00h'),
                     ('4','10:20h às 11:10h'),
                     ('5','11:10h às 12:00h'),
                     ('6','12:10h às 12:50h'),
                     ('7','13:00h às 13:50h'),
                     ('8','13:50h às 14:40h'),
                     ('9','14:40h às 15:30h'),
                     ('10','15:30h às 15:50h'),
                     ('11','15:50h às 16:40h'),
                     ('12','16:40h às 17:30h'),
                     ('13','17:30h às 18:20h'),
                     ('14','19:20h às 20:05h'),
                     ('15','21:10h às 21:55h'),]
    escola = models.ForeignKey(Escola, on_delete=models.CASCADE)
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    laboratorio = models.ForeignKey(Laboratorio, on_delete=models.CASCADE)
    disciplina = models.ForeignKey(Disciplina, on_delete=models.CASCADE)
    turma = models.ForeignKey(Turma, on_delete=models.CASCADE)
    data_agendada = models.DateField()
    horario_agendado = models.CharField(max_length=20, choices=HORARIO_CHOICES)
    data_agendamento = models.DateTimeField(auto_now_add=True)# Data e hora automáticas do agendamento

    def __str__(self):
        return f"Agendamento para {self.disciplina} na data {self.data_agendada} às {self.horario_agendado}"
    
    class Meta:
        # Definindo que a combinação de laboratório, data_agendada e horario_agendado deva ser única
        unique_together = ('laboratorio', 'data_agendada', 'horario_agendado')

Agenda/forms.py
from django import forms
from django.forms.widgets import DateInput
from .models import Agenda

class AgendaModelForm(forms.ModelForm):

    class Meta:
        model = Agenda
        fields = ['escola', 'laboratorio',
                  'disciplina', 'turma', 'data_agendada', 'horario_agendado']
        widgets = {
            'data_agendada': DateInput(attrs={'type': 'date'})
        }

Agenda/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
import pandas as pd
import plotly.express as px

from .forms import AgendaModelForm
from .models import Agenda

def login_user(request):
    return render(request, 'login.html')

def logout_user(request):
    logout(request)
    return redirect('login_user')

def submit_login(request):
    if request.POST:
        username = request.POST.get('username')
        password = request.POST.get('password')
        usuario = authenticate(username=username, password=password)
        if usuario is not None:
            login(request, usuario)
            return redirect('agenda')
        else:
            messages.error(request, "Usuário ou senha inválido")
    return redirect('login_user')

def agenda(request):
    if str(request.user) != 'AnonymousUser':
        user = request.user
        context = {
            'agenda': Agenda.objects.filter(usuario=user)
        }
        return render(request, 'agenda.html', context)
    else:
        return redirect('login_user')

def agendamento(request):
    if str(request.user) != 'AnonymousUser':
        if str(request.method) == 'POST':
            form = AgendaModelForm(request.POST)
            if form.is_valid():
                agenda = form.save(commit=False) # Evita salvar no banco antes de modificar
                agenda.usuario = request.user  # Define o usuário com base no request.user
                agenda.save()
                messages.success(request, 'Agendamento realizado.')
                form = AgendaModelForm() # Comando para limpar o formulário

                messages.success(request, 'Agendamento realizado.')
                form = AgendaModelForm() # Comando para limpar o formulário
            else:
                messages.error(request, 'Erro ao realizar o agendamento.')
        else:
            form = AgendaModelForm()
        context = {
            'form': form
        }
        return render(request, 'agendamento.html', context)
    else:
        return redirect('login_user')

@login_required
def data_analysis(request):
    # Extraindo dados do banco de dados
    agenda_data = Agenda.objects.select_related('disciplina').values('disciplina__nome', 'data_agendada', 'horario_agendado')
    df = pd.DataFrame(agenda_data)

    # Contagem de agendamentos por disciplina
    if not df.empty:
        count_by_disciplina = df['disciplina__nome'].value_counts().reset_index()
        count_by_disciplina.columns = ['Disciplina', 'Count']
        fig = px.bar(count_by_disciplina, x='Disciplina', y='Count', title='Agendamentos por Disciplina')
        graph = fig.to_html(full_html=False)
    else:
        graph = None

    context = {
        'graph': graph,
    }

    return render(request, 'data_analysis.html', context)

Agenda/templates/agenda.html
{% extends "model.html" %}

{% block content %}
<p>
   Olá {{ request.user }}, esta é sua lista de agendamentos:
</p>
<table class="w3-table w3-striped w3-bordered">
    <thead>
        <tr class="w3-red">
            <th>Escola</th>
            <th>Professor</th>
            <th>laboratório</th>
            <th>Disciplina</th>
            <th>Turma</th>
            <th>Data Agendada</th>
            <th>Horario Agendado</th>
        </tr>
    </thead>
    <tbody>
        {% for item in agenda %}
        <tr>
            <td>{{ item.escola }}</td>
            <td>{{ item.usuario }}</td>
            <td>{{ item.laboratorio }}</td>
            <td>{{ item.disciplina }}</td>
            <td>{{ item.turma }}</td>
            <td>{{ item.data_agendada }}</td>
            <td>{{ item.get_horario_agendado_display }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

Agenda/templates/agendamento.html
{% extends "model.html" %}

{% block content %}
<form action="{% url 'agendamento' %}" class="w3-container" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Agendar</button>
</form>
{% endblock %}

Agenda/templates/data_analysis.html
{% extends "model.html" %}

{% block head %}
    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
{% endblock %}

{% block content %}
    <h1 class="w3-center">Análise de Dados</h1>

    <h2 class="w3-center">Gráfico de Agendamentos por Disciplina</h2>
    {% if graph %}
    <div>{{ graph|safe }}</div>
    {% else %}
    <p>Nenhum dado disponível para exibir o gráfico.</p>
    {% endif %}

{% endblock %}

Agenda/templates/login.html
{% extends "model.html" %}

{% block content %}
<!-- <img src="static\logo.jpeg" alt="LabConnect logo" style="width:100%"> -->
<!-- Modal -->
<div id="id01" class="w3-modal">
    <div class="w3-modal-content">
        <div class="w3-container w3-black">
            <!-- <span onclick="document.getElementById('id01').style.display='none'"
                    class="w3-button w3-display-topright">&times;</span> -->
            </form>
            <h3>Entre com usuário e senha para efetuar login</h2>
        </div>
        <div class="w3-container">
            <form action="{% url 'submit_login' %}" method="post">
                {% csrf_token %}
                <p></p>
                <label class="w3-text-blue"><b>Usuário</b></label>
                <input class="w3-input w3-border" type="text" name="username">
                <p></p>
                <label class="w3-text-blue"><b>Senha</b></label>
                <input class="w3-input w3-border" type="password" name="password">
                <p></p>
                <button class="w3-btn w3-red">Entrar</button>
                <p></p>
        </div>
        <div class="w3-container w3-black">
            <p></p>
            <p></p>
        </div>
    </div>
</div>

<!-- Popup -->
<div id="popup" class="w3-modal">
    <div class="w3-modal-content w3-card-4 w3-animate-top">
        <header class="w3-container w3-red">
            <span onclick="closePopup()" class="w3-button w3-display-topright">&times;</span>
            <h2>Erro!</h2>
        </header>
        <div class="w3-container">
            <p id="error-message"></p>
        </div>
    </div>
</div>

<script>
    // Função para abrir o modal quando a página carregar
    window.onload = function () {
        document.getElementById('id01').style.display = 'block';
    };

    // Função para exibir o popup de erro
    function showErrorPopup(message) {
        document.getElementById('error-message').innerHTML = message;
        document.getElementById('popup').style.display = 'block';
    }
    // Verifica se há mensagens de erro e exibe o popup
    {% if messages %}
    window.onload = function () {
        showErrorPopup("{% for message in messages %}{{ message }}{% endfor %}");
    };
    {% endif %}
    function closePopup() {
        document.getElementById('popup').style.display = 'none';
        location.reload(); // Recarrega a página
    }
</script>
{% endblock %}

Agenda/templates/model.html
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <title>LabConnect</title>
    {% block head %} {% endblock %}
</head>

<body>
    <div class="w3-bar w3-black">
        <a href="/" class="w3-bar-item w3-button">Agenda</a>
        <a href="/agendamento" class="w3-bar-item w3-button">Agendamento</a>
        <a href="/admin" class="w3-bar-item w3-button">Painel Agministrativo</a>
        {% if request.user.is_superuser %}
        <a href="/data-analysis" class="w3-bar-item w3-button">Análise</a>
        {% endif %}
        <a href="/logout" class="w3-bar-item w3-button">Sair</a>
    </div>
    <div>
        <p></p>
        {% block content %} {% endblock %}
    </div>
    <div class="w3-display-middle w3-green w3-round">
        {% for message in messages %}
        {{ message }}
        {% endfor %}
    </div>
</body>

</html>